title: "OSCAL"
baseURL: https://pages.nist.gov/OSCAL/
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "uswds"
googleAnalytics: UA-42404149-54
canonifyurls: true
enableGitInfo: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
params:
  header:
    project_shortname: "OSCAL"
    project_name: "OSCAL: the Open Security Controls Assessment Language"
  contentRepoPath: https://github.com/usnistgov/OSCAL/tree/master/docs/content
  searchAffiliate: oscal
  sidenav:
#    activerenderdepth: 2
#    inactiverenderdepth: 5
menu:
  secondary:
  - name: Github
    url: https://github.com/usnistgov/OSCAL
    weight: 90
module:
  mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: ../xml
    target: static/artifacts/xml
  - source: ../json
    target: static/artifacts/json
  - source: ../content
    target: static/artifacts/content
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes
